namespace SocialPay.Core.Configurations
{
    public class AppSettings
    {
        public string appKey { get; set; }
        public string appId { get; set; }
        public string SecretKey { get; set; }
        public string SterlingBankCode { get; set; }
        public string BaseApiUrl { get; set; }
        public string EwsServiceUrl { get; set; }
        public string LdapServiceUrl { get; set; }
        public string IBSserviceUrl { get; set; }
        public string nfpliveBaseUrl { get; set; }
        public string WebportalUrl { get; set; }
        public string BankServiceUrl { get; set; }
        public string nameEnquiryRequestType { get; set; }
        public string getBanksRequestType { get; set; }
        public string currencyCode { get; set; }
        public string walletBaseUrl { get; set; }
        public string createwalletUrl { get; set; }
        public string paymentlinkUrl { get; set; }
        public string walletExtensionUrl { get; set; }
        public string walletTowalletUrl { get; set; }
        public string sterlingpaymentGatewayRequestUrl { get; set; }
        public string paywithSpectaBaseUrl { get; set; }
        public string paywithSpectaverifyPaymentUrl { get; set; }
        public string paywithSpectaCallBackUrl { get; set; }
        public string paywithSpectaPurchaseUrlExtension { get; set; }
        public string createSpectaUrlExtension { get; set; }
        public string paywithspectaHeaderKey { get; set; }
        public string paywithspectaHeaderValue { get; set; }
        public string mid { get; set; }
        public string paymentCombination { get; set; }
        public string deliverySLA { get; set; }
        public string MerchantLinkPaymentDocument { get; set; }
        public string DisputeDocument { get; set; }
        public string PaymentLinkPercentage { get; set; }
        public string EmailTemplatesPath { get; set; }
        public string InvoiceTemplateDescription { get; set; }
        public string receiptTemplateDescription { get; set; }
        public string paywithspectamerchanId { get; set; }
        public string invoicePaymentlinkUrl { get; set; }
        public string clearwalletUrl { get; set; }
        public string accountResetToken { get; set; }
        public string newpasswordUrl { get; set; }
        public string walletcurrencyCode { get; set; }
        public string SterlingWalletPoolAccount { get; set; }
        public string getwalletDetailsUrl { get; set; }
        public string fioranoBaseUrl { get; set; }
        public string fioranoFundsTransferUrl { get; set; }
        public string fioranoCommisionCode { get; set; }
        public string fioranoVtellerAppID { get; set; }
        public string fioranoTrxnLocation { get; set; }
        public string fioranoTransactionType { get; set; }
        public string fioranoDebitCurrency { get; set; }
        public string fioranoCreditCurrency { get; set; }
        public string transactionNarration { get; set; }
        public string socialPayNominatedAccountNo { get; set; }
        public string socialT24AccountNo { get; set; }
        public string socialT24Bracode { get; set; }
        public string returnedDateSLA { get; set; }
        public string socialPayT24CustomerNum { get; set; }
        public string socialPayT24AccountName { get; set; }
        public string socialPayT24CustomerLedCode { get; set; }
        public string nipdbConnectionString { get; set; }
        public string socialPayAppID { get; set; }
        public string socialPayT24CurCode { get; set; }
        public string socialT24BVN { get; set; }
        public string clientloginAttempts { get; set; }
        public string otpSession { get; set; }
        public string redisServer { get; set; }
        public string redisInstanceName { get; set; }
        public string tinvalidationBaseUrl { get; set; }
        public string tinvalidationEndpointUrl { get; set; }
        public string accountLock { get; set; }
        public string accountReason { get; set; }
        public string nameEnquiryChannelCode { get; set; }
        public string senderEmailInfo { get; set; }
        public string senderEmailName { get; set; }
        public string successfulTransactionEmailSubject { get; set; }
        public string failedTransactionEmailSubject { get; set; }
        public string sharedkeyval { get; set; }
        public string sharedvectorval { get; set; }
        public string ageLimit { get; set; }
        public string WalletSecretKey { get; set; }
        public string WalletVector { get; set; }
        public string sendGridAPIBaseUrl { get; set; }
        public string sendGridEmailUrlExtension { get; set; }
        public string sendGridbearerToken { get; set; }
        public string sendGridEmailSender { get; set; }
        public string MerchantSignUpEmailSubject { get; set; }
        public decimal vat { get; set; }
        public string nibsQRCodeBaseUrl { get; set; }
        public string nibsQRCodeCreateMerchantUrl { get; set; }
        public string nibsQRCodeXClientHeaderName { get; set; }
        public string nibsQRCodeXClientHeaderValue { get; set; }
        public string nibsQRCodeCheckSumHeaderName { get; set; }
        public string nibsQRCodeClientKey { get; set; }
        public string nibsQRCodeClientSecret { get; set; }
    }
}
